# Generated by Django 2.0.4 on 2018-05-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180421_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
