# Generated by Django 2.0.4 on 2018-05-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_file',
            field=models.FileField(upload_to=''),
        ),
    ]
