# Generated by Django 2.0.4 on 2018-05-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180513_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
